In [2]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import datetime
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
data = pd.read_csv('D://datasets/bitcoin_data.csv')
data

Timestamp      Open      High       Low     Close  Volume_(BTC)  \
0        1325317920      4.39      4.39      4.39      4.39      0.455581   
1        1325317980       NaN       NaN       NaN       NaN           NaN   
2        1325318040       NaN       NaN       NaN       NaN           NaN   
3        1325318100       NaN       NaN       NaN       NaN           NaN   
4        1325318160       NaN       NaN       NaN       NaN           NaN   
...             ...       ...       ...       ...       ...           ...   
4857372  1617148560  58714.31  58714.31  58686.00  58686.00      1.384487   
4857373  1617148620  58683.97  58693.43  58683.97  58685.81      7.294848   
4857374  1617148680  58693.43  58723.84  58693.43  58723.84      1.705682   
4857375  1617148740  58742.18  58770.38  58742.18  58760.59      0.720415   
4857376  1617148800  58767.75  58778.18  58755.97  58778.18      2.712831   

         Volume_(Currency)  Weighted_Price  
0                 2.000000        4.390000  
1                      NaN             NaN  
2                      NaN             NaN  
3                      NaN             NaN  
4                      NaN             NaN  
...                    ...             ...  
4857372       81259.372187    58692.753339  
4857373      428158.146640    58693.226508  
4857374      100117.070370    58696.198496  
4857375       42332.958633    58761.866202  
4857376      159417.751000    58764.349363  

[4857377 rows x 8 columns]

In [10]:
data.isnull().sum(axis=0)

Timestamp                  0
Open                 1243608
High                 1243608
Low                  1243608
Close                1243608
Volume_(BTC)         1243608
Volume_(Currency)    1243608
Weighted_Price       1243608
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4857377 entries, 0 to 4857376
Data columns (total 8 columns):
 #   Column             Dtype  
---  ------             -----  
 0   Timestamp          int64  
 1   Open               float64
 2   High               float64
 3   Low                float64
 4   Close              float64
 5   Volume_(BTC)       float64
 6   Volume_(Currency)  float64
 7   Weighted_Price     float64
dtypes: float64(7), int64(1)
memory usage: 296.5 MB


In [6]:
data.describe()

Timestamp          Open          High           Low         Close  \
count  4.857377e+06  3.613769e+06  3.613769e+06  3.613769e+06  3.613769e+06   
mean   1.471301e+09  6.009024e+03  6.013357e+03  6.004488e+03  6.009014e+03   
std    8.428019e+07  8.996247e+03  9.003521e+03  8.988778e+03  8.996360e+03   
min    1.325318e+09  3.800000e+00  3.800000e+00  1.500000e+00  1.500000e+00   
25%    1.398179e+09  4.438600e+02  4.440000e+02  4.435200e+02  4.438600e+02   
50%    1.471428e+09  3.596970e+03  3.598190e+03  3.595620e+03  3.597000e+03   
75%    1.544288e+09  8.627270e+03  8.632980e+03  8.621090e+03  8.627160e+03   
max    1.617149e+09  6.176356e+04  6.178183e+04  6.167355e+04  6.178180e+04   

       Volume_(BTC)  Volume_(Currency)  Weighted_Price  
count  3.613769e+06       3.613769e+06    3.613769e+06  
mean   9.323249e+00       4.176284e+04    6.008935e+03  
std    3.054989e+01       1.518248e+05    8.995992e+03  
min    0.000000e+00       0.000000e+00    3.800000e+00  
25%    4.097759e-01       4.521422e+02    4.438306e+02  
50%    1.979811e+00       3.810124e+03    3.596804e+03  
75%    7.278216e+00       2.569821e+04    8.627637e+03  
max    5.853852e+03       1.390067e+07    6.171621e+04

In [48]:
data['Timestamp'] = data['Timestamp'].apply(lambda x: datetime.datetime.fromtimestamp(x))
data

Timestamp      Open      High       Low     Close  \
0       2011-12-31 13:22:00      4.39      4.39      4.39      4.39   
1       2011-12-31 13:23:00       NaN       NaN       NaN       NaN   
2       2011-12-31 13:24:00       NaN       NaN       NaN       NaN   
3       2011-12-31 13:25:00       NaN       NaN       NaN       NaN   
4       2011-12-31 13:26:00       NaN       NaN       NaN       NaN   
...                     ...       ...       ...       ...       ...   
4857372 2021-03-31 05:26:00  58714.31  58714.31  58686.00  58686.00   
4857373 2021-03-31 05:27:00  58683.97  58693.43  58683.97  58685.81   
4857374 2021-03-31 05:28:00  58693.43  58723.84  58693.43  58723.84   
4857375 2021-03-31 05:29:00  58742.18  58770.38  58742.18  58760.59   
4857376 2021-03-31 05:30:00  58767.75  58778.18  58755.97  58778.18   

         Volume_(BTC)  Volume_(Currency)  Weighted_Price  
0            0.455581           2.000000        4.390000  
1                 NaN                NaN             NaN  
2                 NaN                NaN             NaN  
3                 NaN                NaN             NaN  
4                 NaN                NaN             NaN  
...               ...                ...             ...  
4857372      1.384487       81259.372187    58692.753339  
4857373      7.294848      428158.146640    58693.226508  
4857374      1.705682      100117.070370    58696.198496  
4857375      0.720415       42332.958633    58761.866202  
4857376      2.712831      159417.751000    58764.349363  

[4857377 rows x 8 columns]

In [6]:
from torchvision import transforms
p = torch.tensor([[[2,2,2,2],
                [4,4,4,4],
                [6,6,6,6]]], dtype=torch.float32)
# print(p.shape)
# x = p.view(3,-1)
# y = p.mean(dim=1, keepdim=True)
# s = p.std(dim=1, keepdims=True)
# print(y)
# print(s)
# transform = transforms.Normalize(mean=y, std=s)
# out = transform(x)
# print(out)
mean = p.view(-1,3).mean(dim=1)
print(mean)

tensor([2.0000, 3.3333, 4.6667, 6.0000])


In [7]:
print(p)

tensor([[[2., 2., 2., 2.],
         [4., 4., 4., 4.],
         [6., 6., 6., 6.]]])


In [75]:
x = torch.ones((3,1))
y = torch.ones((3))

print(y)

tensor([1., 1., 1.])


In [69]:
x = np.ones((1,3))
x.mean(axis = 0)

array([1., 1., 1.])

In [5]:
x = torch.ones(2)
x[1] = 0
x

tensor([1., 0.])